name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice
version: 0.3.2
homepage: https://github.com/lejard-h/flutter_google_places

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.2.0
  google_maps_webservice: 
    git:
      url: https://github.com/shkvoretz/google_maps_webservice.git
      ref: 752f417c9ab559889b2a73b4cda331ea61913259
  http: ^1.0.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
